### ISSUE TITLE
Error compiling 0.8.25 solidity version

### ISSUE THREAD

**Issue by agsola** [matter-labs/zksolc-bin#20]
When trying to compile 0.8.25 contracts, I'm getting this error:

```
Compiling contracts for zkSync Era with zksolc v1.4.0 and solc v0.8.25
Compiling 78 Solidity files
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
```

IMHO it should alert if 0.8.25 is not supported, if it is the case.

**Comment by janjakubnanista** [comment]
Hey @agsola! The solution that worked for me, after debugging the `solc` JavaScript wrapper, was to explicitly add `solc` as a dependency to my `package.json`.

The issue comes from the fact that inside the `solc` JavaScript wrapper, a call is made to `require` a module. The module  's name is resolved dynamically from `solc/wrapper` - if you don't have `solc` installed, this will result in an undefined module name which will break the consequent `require` call

**Comment by hedgar2017** [comment]
Sounds like a case Hardhat should handle.

cc @MexicanAce @githubdoramon

**Comment by uF4No** [comment]
Tested without issues compiling multiple contracts with solc 0.8.25 and zksolc 1.5.x.

If you face this or any other issues, please [create a thread in our GitHub Discussions page](https://github.com/zkSync-Community-Hub/zksync-developers/discussions) and we'll help 🤙
